#############################################################################
# Makefile for building: delta
# Generated by qmake (3.1) (Qt 5.12.3)
# Project:  delta.pro
# Template: app
# Command: /home/anton/Qt/5.12.3/gcc_64/bin/qmake -o Makefile delta.pro -spec linux-g++ CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -fopenmp -O3 -march=native -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/home/anton/Qt/5.12.3/gcc_64/mkspecs/linux-g++
QMAKE         = /home/anton/Qt/5.12.3/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/anton/Qt/5.12.3/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/anton/Qt/5.12.3/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = delta1.0.0
DISTDIR = /home/anton/Desktop/Мат+/Δelta/Δ4/Project/.tmp/delta1.0.0
LINK          = g++
LFLAGS        = -fopenmp -Wl,-O1
LIBS          = $(SUBLIBS)    
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = diff_operators.cpp \
		diffeq_solvers.cpp \
		drawer.cpp \
		grids.cpp \
		logger.cpp \
		main.cpp \
		matrix.cpp \
		scene.cpp \
		slae_solvers.cpp 
OBJECTS       = diff_operators.o \
		diffeq_solvers.o \
		drawer.o \
		grids.o \
		logger.o \
		main.o \
		matrix.o \
		scene.o \
		slae_solvers.o
DIST          = /home/anton/Qt/5.12.3/gcc_64/mkspecs/features/spec_pre.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/unix.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/linux.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/sanitize.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/g++-base.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/g++-unix.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/qconfig.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/resources.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/qtquickcompiler.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf \
		delta.pro bitmap_image.hpp \
		diff_operators.h \
		diffeq_solvers.h \
		drawer.h \
		grids.h \
		logger.h \
		matrix.h \
		scene.h \
		\ \
		slae_solvers.h diff_operators.cpp \
		diffeq_solvers.cpp \
		drawer.cpp \
		grids.cpp \
		logger.cpp \
		main.cpp \
		matrix.cpp \
		scene.cpp \
		slae_solvers.cpp
QMAKE_TARGET  = delta
DESTDIR       = 
TARGET        = delta


first: all
####### Build rules

delta:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: delta.pro /home/anton/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf /home/anton/Qt/5.12.3/gcc_64/mkspecs/features/spec_pre.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/unix.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/linux.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/sanitize.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/g++-base.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/g++-unix.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/qconfig.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/resources.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/qtquickcompiler.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf \
		/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf \
		delta.pro
	$(QMAKE) -o Makefile delta.pro -spec linux-g++ CONFIG+=qtquickcompiler
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/spec_pre.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/unix.conf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/linux.conf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/sanitize.conf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base.conf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/g++-base.conf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/common/g++-unix.conf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/qconfig.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/qt_functions.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/qt_config.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/toolchain.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/default_pre.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/resolve_config.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/default_post.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/resources.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/qtquickcompiler.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/warn_on.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/qmake_use.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/file_copies.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/testcase_targets.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/exceptions.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/yacc.prf:
/home/anton/Qt/5.12.3/gcc_64/mkspecs/features/lex.prf:
delta.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile delta.pro -spec linux-g++ CONFIG+=qtquickcompiler

qmake_all: FORCE


all: Makefile delta

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_qmlcache_make_all:
compiler_qmlcache_clean:
compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

diff_operators.o: diff_operators.cpp diffeq_solvers.h \
		grids.h \
		slae_solvers.h \
		matrix.h \
		logger.h \
		diff_operators.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diff_operators.o diff_operators.cpp

diffeq_solvers.o: diffeq_solvers.cpp diffeq_solvers.h \
		grids.h \
		slae_solvers.h \
		matrix.h \
		logger.h \
		diff_operators.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diffeq_solvers.o diffeq_solvers.cpp

drawer.o: drawer.cpp bitmap_image.hpp \
		drawer.h \
		matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawer.o drawer.cpp

grids.o: grids.cpp grids.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grids.o grids.cpp

logger.o: logger.cpp logger.h \
		matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o logger.cpp

main.o: main.cpp diffeq_solvers.h \
		grids.h \
		slae_solvers.h \
		matrix.h \
		logger.h \
		diff_operators.h \
		drawer.h \
		bitmap_image.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

matrix.o: matrix.cpp matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matrix.o matrix.cpp

scene.o: scene.cpp scene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scene.o scene.cpp

slae_solvers.o: slae_solvers.cpp slae_solvers.h \
		matrix.h \
		logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o slae_solvers.o slae_solvers.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

